import type { Template, Presentation, Slide } from "@/types";

export const TEMPLATES: Template[] = [
  {
    id: "academic-blue",
    name: "Academic Blue",
    description: "Clean and professional for academic presentations",
    thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=250&fit=crop",
    category: "academic",
    theme: {
      primary: "#3b82f6",
      secondary: "#8b5cf6",
      background: "#f8fafc",
      text: "#1e293b",
      font: "Inter",
    },
  },
  {
    id: "dark-tech",
    name: "Dark Tech",
    description: "Modern dark theme for tech and science topics",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=250&fit=crop",
    category: "tech",
    theme: {
      primary: "#6366f1",
      secondary: "#a78bfa",
      background: "#0f172a",
      text: "#f1f5f9",
      font: "Sora",
    },
  },
  {
    id: "minimal-white",
    name: "Minimal White",
    description: "Ultra-clean minimal design for any subject",
    thumbnail: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=250&fit=crop",
    category: "minimal",
    theme: {
      primary: "#1e293b",
      secondary: "#475569",
      background: "#ffffff",
      text: "#0f172a",
      font: "Inter",
    },
  },
  {
    id: "gradient-creative",
    name: "Gradient Creative",
    description: "Vibrant gradients for creative subjects",
    thumbnail: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=400&h=250&fit=crop",
    category: "creative",
    theme: {
      primary: "#f59e0b",
      secondary: "#ec4899",
      background: "#fdf4ff",
      text: "#1e293b",
      font: "Sora",
    },
    isPro: true,
  },
  {
    id: "corporate-navy",
    name: "Corporate Navy",
    description: "Professional business presentation style",
    thumbnail: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=400&h=250&fit=crop",
    category: "business",
    theme: {
      primary: "#1e40af",
      secondary: "#0284c7",
      background: "#f0f9ff",
      text: "#0f172a",
      font: "Inter",
    },
  },
  {
    id: "nature-green",
    name: "Nature Green",
    description: "Earthy tones for environmental topics",
    thumbnail: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=250&fit=crop",
    category: "academic",
    theme: {
      primary: "#059669",
      secondary: "#0891b2",
      background: "#f0fdf4",
      text: "#0f2a1a",
      font: "Inter",
    },
    isPro: true,
  },
];

export const MOCK_SLIDES: Slide[] = [
  {
    id: "s1",
    layout: "title",
    title: "Introduction to Machine Learning",
    subtitle: "Understanding the Fundamentals of AI-Driven Systems",
    speakerNotes: "Welcome the audience. Introduce the main objectives of today's class.",
    imageUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&h=450&fit=crop",
  },
  {
    id: "s2",
    layout: "content",
    title: "What is Machine Learning?",
    bullets: [
      "A subset of Artificial Intelligence (AI)",
      "Algorithms that learn from data without explicit programming",
      "Enables computers to improve from experience",
      "Three main types: Supervised, Unsupervised, Reinforcement",
    ],
    imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&h=450&fit=crop",
    speakerNotes: "Explain the three types with simple analogies. Supervised = teacher guiding student.",
  },
  {
    id: "s3",
    layout: "image-right",
    title: "Key Applications",
    bullets: [
      "Image and facial recognition",
      "Natural language processing",
      "Recommendation systems",
      "Autonomous vehicles",
      "Medical diagnosis",
    ],
    imageUrl: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=450&fit=crop",
    speakerNotes: "Use Netflix and Spotify as familiar recommendation examples.",
  },
  {
    id: "s4",
    layout: "chart",
    title: "ML Adoption Growth (2020–2025)",
    chartData: {
      type: "bar",
      labels: ["2020", "2021", "2022", "2023", "2024", "2025"],
      datasets: [{ label: "Adoption Rate (%)", data: [22, 38, 52, 67, 78, 89], color: "#6366f1" }],
    },
    speakerNotes: "Highlight the 4x growth in just 5 years.",
  },
  {
    id: "s5",
    layout: "two-column",
    title: "Supervised vs Unsupervised Learning",
    bullets: ["Labeled training data", "Clear target output", "Classification/Regression", "Higher accuracy"],
    imageUrl: "https://images.unsplash.com/photo-1591696205602-2f950c417cb9?w=800&h=450&fit=crop",
    speakerNotes: "Use left panel for supervised, right for unsupervised.",
  },
  {
    id: "s6",
    layout: "content",
    title: "Neural Networks Explained",
    bullets: [
      "Inspired by the human brain structure",
      "Layers: Input, Hidden, Output",
      "Learns through backpropagation",
      "Deep learning = many hidden layers",
    ],
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=450&fit=crop",
    speakerNotes: "Draw a simple 3-layer diagram on the board.",
  },
  {
    id: "s7",
    layout: "title",
    title: "Summary & Key Takeaways",
    subtitle: "ML is transforming every industry — understanding its fundamentals is essential for future innovators.",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=450&fit=crop",
    speakerNotes: "Open Q&A session. Mention the next class topic.",
  },
];

export const MOCK_PRESENTATIONS: Presentation[] = [
  {
    id: "p1",
    title: "Introduction to Machine Learning",
    description: "Converted from lecture transcript",
    slides: MOCK_SLIDES,
    templateId: "dark-tech",
    theme: TEMPLATES[1].theme,
    sourceType: "transcript",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    status: "ready",
    slideCount: 7,
    thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&h=250&fit=crop",
  },
  {
    id: "p2",
    title: "Organic Chemistry: Reaction Mechanisms",
    description: "Generated from PDF notes",
    slides: [],
    templateId: "academic-blue",
    theme: TEMPLATES[0].theme,
    sourceType: "pdf",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    status: "ready",
    slideCount: 12,
    thumbnail: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&h=250&fit=crop",
  },
  {
    id: "p3",
    title: "World History: The Renaissance",
    description: "Converted from class recording",
    slides: [],
    templateId: "minimal-white",
    theme: TEMPLATES[2].theme,
    sourceType: "url",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    status: "ready",
    slideCount: 9,
    thumbnail: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=400&h=250&fit=crop",
  },
];

export const PROCESSING_STEPS = [
  { id: "parse", label: "Parsing Content", description: "Extracting text and structure from your file" },
  { id: "analyze", label: "AI Analysis", description: "Understanding topics, key concepts, and flow" },
  { id: "outline", label: "Generating Outline", description: "Creating logical slide structure" },
  { id: "slides", label: "Building Slides", description: "Writing titles, bullets, and speaker notes" },
  { id: "images", label: "Adding Visuals", description: "Sourcing relevant images for each slide" },
  { id: "design", label: "Applying Design", description: "Applying your chosen template and theme" },
  { id: "export", label: "Finalizing PPTX", description: "Preparing your presentation for download" },
];

export const STAT_CARDS = [
  { label: "Presentations Created", value: "3", icon: "📊", trend: "+1 this week" },
  { label: "Slides Generated", value: "28", icon: "📄", trend: "+7 this week" },
  { label: "Time Saved", value: "4.5h", icon: "⏱️", trend: "vs manual creation" },
  { label: "AI Credits Left", value: "85", icon: "✨", trend: "out of 100" },
];
